# Generated by Django 5.0.6 on 2025-05-29 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0003_buyingrecords_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingrecords',
            name='total_paid',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('effective', 'Efectivo'), ('transfer', 'Transferencia'), ('movil_pay', 'Pago Móvil')], max_length=20)),
                ('amount', models.FloatField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('buying_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='buying.buyingrecords')),
            ],
        ),
    ]
