# Generated by Django 5.0.6 on 2025-01-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kind_of_person',
            field=models.CharField(choices=[('client', 'Client'), ('operator', 'Operator'), ('admin', 'Admin')], default='user', max_length=255),
        ),
    ]
