# Generated by Django 5.0.6 on 2025-02-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_account_kind_of_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='document',
            field=models.CharField(null=True, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(null=True, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='rif',
            field=models.CharField(null=True, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
