# Generated by Django 5.0.6 on 2025-02-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_account_document_account_phone_account_rif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='document',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='rif',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
