# Generated by Django 5.0.6 on 2025-04-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reset_password_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='reset_password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
