# Generated by Django 5.0.6 on 2024-12-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbatch',
            name='operator',
        ),
    ]
