# Generated by Django 5.0.6 on 2025-01-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_productbatch_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
