# Generated by Django 5.0.6 on 2025-01-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_price_unit_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='price_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
