# Generated by Django 5.0.6 on 2025-01-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_productbatch_price_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
