# Generated by Django 5.0.6 on 2025-01-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_movement_quantity'),
        ('purchase', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.order'),
        ),
    ]
