# Generated by Django 5.0.6 on 2025-01-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productbatch_purchase_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbatch',
            name='product_variant',
        ),
    ]
