# Generated by Django 5.0.6 on 2025-01-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='safety_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='waste',
        ),
    ]
