# Generated by Django 5.0.6 on 2025-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_product_expiration_remove_product_location_and_more'),
        ('purchase', '0009_order_real_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.AddField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(blank=True, related_name='products', to='purchase.provider'),
        ),
    ]
