# Generated by Django 5.0.6 on 2025-06-01 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_product_provider_product_providers'),
        ('purchase', '0010_order_consignment_status_order_credit_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='consignment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_batches', to='purchase.order'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='is_consignment',
            field=models.BooleanField(default=False),
        ),
    ]
