# Generated by Django 5.0.6 on 2025-06-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_productbatch_consignment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
