# Generated by Django 5.0.6 on 2025-06-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_productbatch_sold_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='initial_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
