# Generated by Django 5.0.6 on 2025-01-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_unit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
