# Generated by Django 5.0.6 on 2025-02-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_order_price_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='document',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='rif',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
