# Generated by Django 5.0.6 on 2025-02-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_provider_document_provider_rif_alter_provider_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='real_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
