# Generated by Django 5.0.6 on 2025-06-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_order_real_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='consignment_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcialmente vendido'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sold_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
