# Generated by Django 5.0.6 on 2025-06-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_order_consignment_status_order_credit_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('COUNTED', 'Contado'), ('CREDIT', 'Crédito'), ('CONSIGNATION', 'consignation')], default='COUNTED', max_length=20, null=True),
        ),
    ]
