# Generated by Django 5.0.6 on 2025-06-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_paid',
            field=models.BooleanField(default=False),
        ),
    ]
