# Generated by Django 5.0.6 on 2025-06-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_order_credit_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='compensation_type',
            field=models.CharField(blank=True, choices=[('money', 'Monetario'), ('productos', 'Productos')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='compensed',
            field=models.BooleanField(default=True),
        ),
    ]
