# Generated by Django 5.0.6 on 2025-06-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_order_compensation_type_order_compensed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='compensation_type',
            field=models.CharField(blank=True, choices=[('money', 'Monetario'), ('product', 'Productos')], max_length=30, null=True),
        ),
    ]
