# Generated by Django 5.0.6 on 2025-06-08 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_alter_order_compensation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='compensation_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_orders', to='purchase.order'),
        ),
    ]
