# Generated by Django 5.0.6 on 2025-06-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_order_compensation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='compensation_order',
        ),
        migrations.AddField(
            model_name='order',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
